### ISSUE TITLE
vmrun problem due to missing arg

### ISSUE THREAD

**Issue by dawiss** [hashicorp/vagrant-vmware-desktop#31]
### Vagrant version

2.2.18

### Vagrant VMware plugin version

3.0.1, global

### Vagrant VMware utility version

1.0.20

### vmrun version

1.17.0

### Vmware Workstation version

16.2.0

### Host operating system

Arch Linux

### Guest operating system

CentOS 7, but tried others

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
end
```

### Debug output

https://gist.github.com/dawiss/e05d58f278f7ecb974e87dbbdf4b5545

### Expected behavior

Working vm 

### Actual behavior

VM is not starting.

### Steps to reproduce

1. vagrant up

It's not working due to missing arg -T ws - ws in my case for workstation. If I run it manually with -T ws it works fine. I haven't tried yet to downgrade my vmrun. It will probably fix this problem for now.

**Comment by s0undt3ch** [comment]
Same issue here.

**Comment by jovmarkovic** [comment]
Same issue with worstation pro 17:
`vmrun version 1.17.0 build-20800274`
Plugin version: 
`vagrant-vmware-desktop (3.0.1, global)
`
Uitility version: 
`vagrant-vmware-utility 1.0.21-1`

Vagrant up works when clone is disabled, this is currently mandatory:
```
config.vm.provider "vmware_desktop" do |v|
  v.linked_clone = false
end
```

**Comment by pauby** [comment]
This has been completed, but not released. I don't feel closing the issue before the release happens is a great idea. It looks like it's 'fixed' when it's very much not.

Since we've not had a release since 2021, do we have a date when this can happen? Would avoid me, and I'm assuming others, having to manually apply this fix every time I install this on a fresh machine.
